version: '3'

services:
  # app:
  #   container_name: node_api
  #   build:
  #     context: .
    # links:
    #   - db
    # ports:
    #   - "3001:3001"
    # depends_on:
    #   - db
    # command: npm run dev

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mycontacts
    ports:
      - "5432:5432"
