on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Publish new image
        run: |
          docker login --username fabioseixas --password {{ secrets.GH_TOKEN_FABIO }} ghcr.io
          docker build . --tag ghcr.io/fabioseixas/api-js-ci-end2end:latest
          docker push ghcr.io/fabioseixas/js-api-ci-end2end:latest



