on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Publish new image
        run: |
          echo "{{ secrets.GH_TOKEN_FABIO }}" | docker login ghcr.io -u fabioseixas --password-stdin
          docker build . --tag ghcr.io/fabioseixas/api-js-ci-end2end:latest
          docker push ghcr.io/fabioseixas/js-api-ci-end2end:latest



