on: push

jobs:
  end2end:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: root
          POSTGRES_DB: mycontacts

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: run migrations
        run: npm run db:setup
